export enum RuleEnum {
  // APP COMPANY SETTING
  CAN_SHOW_SETTING = 'CAN_SHOW_SETTING',
  // PRODUCT
  CAN_SHOW_PRODUCT = 'CAN_SHOW_PRODUCT',
  CAN_SHOW_PRODUCT_LIST = 'CAN_SHOW_PRODUCT_LIST',
  CAN_UPDATE_PRODUCT = 'CAN_UPDATE_PRODUCT',
  // CATEGORY
  CAN_SHOW_CATEGORY = 'CAN_SHOW_CATEGORY',
  CAN_SHOW_CATEGORY_LIST = 'CAN_SHOW_CATEGORY_LIST',
  // ATTRIBUTE
  CAN_SHOW_ATTRIBUTE = 'CAN_SHOW_ATTRIBUTE',
  CAN_SHOW_ATTRIBUTE_LIST = 'CAN_SHOW_ATTRIBUTE_LIST',
  // OPERATION
  CAN_SHOW_OPERATION_LIST = 'CAN_SHOW_OPERATION_LIST',
  CAN_SHOW_OWN_OPERATION_LIST = 'CAN_SHOW_OWN_OPERATION_LIST',
  // PACKAGES
  CAN_SHOW_PACK_LIST = 'CAN_SHOW_PACK_LIST',
  CAN_SHOW_PACK = 'CAN_SHOW_PACK',
  // COMPANY
  CAN_SHOW_COMPANY = 'CAN_SHOW_COMPANY',
  CAN_SHOW_COMPANY_LIST = 'CAN_SHOW_COMPANY_LIST',
  // DEMAND
  CAN_SHOW_DEMAND_LIST = 'CAN_SHOW_DEMAND_LIST',
}
